name: moodmapper
description: MoodMapper Quantum Edition - Flutter skeleton
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  just_audio: ^0.9.18
  provider: ^6.0.0
