name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Build docs
        run: |
          pandoc docs/mvp.md -s -o docs/index.html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: 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
          publish_dir: ./docs
